### ISSUE TITLE
Table 2

### ISSUE THREAD

**Issue by dmitrijsk** [salesforce/BOLAA#7]
Hi, thanks for your paper! It's a very valuable review of agent architectures and their backbones! A few things:

1. I noticed that in Table 2, the highest average recall using vicuna-7b belongs to ReAct, while it's not in bold.
![image](https://github.com/salesforce/BOLAA/assets/42183699/9fdec6c9-5fcf-4dd9-b050-111f38fb65ba)

2. Did you consider the variance in results when determining the winner (i.e., bold and underlined entries)? Or is it just the maximum value?

Many thanks!
Dmitrijs

**Comment by JimSalesforce** [comment]
Thanks for pointing it out! I believe it is a typo. We will fix it later.

**Comment by dmitrijsk** [comment]
Thanks! Could you please take a look at the second question up there about the variance?

**Comment by JimSalesforce** [comment]
That's a good point! However, due to resources limitation, we didn't do the variance study. We only include the best performance in all runnings.

**Comment by dmitrijsk** [comment]
Clear, thanks!
